<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8">
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

  <title>ORGANIZE LIFES || To Do List || FrameWork</title>


  <meta name="description"
    content="Most Powerful &amp; Comprehensive Bootstrap 5 Admin Dashboard built for developers!">
  <meta name="keywords" content="dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5">
  <!-- Canonical SEO -->
  <link rel="canonical" href="https://themeselection.com/item/sneat-dashboard-pro-bootstrap/">


  <!-- ? PROD Only: Google Tag Manager (Default ThemeSelection: GTM-5DDHKGP, PixInvent: GTM-5J3LMKC) -->
  <script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-5DDHKGP"></script>
  <script>(function (w, d, s, l, i) {
      w[l] = w[l] || []; w[l].push({
        'gtm.start':
          new Date().getTime(), event: 'gtm.js'
      }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
          'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-5DDHKGP');</script>
  <!-- End Google Tag Manager -->

  <!-- Favicon -->
  <link rel="icon" type="image/svg+xml"
    href="data:image/svg+xml,%3Csvg class='w-[46px] h-[46px] text-blue-500' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' width='24' height='24' fill='none' viewBox='0 0 24 24'%3E%3Cpath stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M21 12a28.076 28.076 0 0 1-1.091 9M7.231 4.37a8.994 8.994 0 0 1 12.88 3.73M2.958 15S3 14.577 3 12a8.949 8.949 0 0 1 1.735-5.307m12.84 3.088A5.98 5.98 0 0 1 18 12a30 30 0 0 1-.464 6.232M6 12a6 6 0 0 1 9.352-4.974M4 21a5.964 5.964 0 0 1 1.01-3.328 5.15 5.15 0 0 0 .786-1.926m8.66 2.486a13.96 13.96 0 0 1-.962 2.683M7.5 19.336C9 17.092 9 14.845 9 12a3 3 0 1 1 6 0c0 .749 0 1.521-.031 2.311M12 12c0 3 0 6-2 9'/%3E%3C/svg%3E">

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link
    href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;display=swap"
    rel="stylesheet">


  <link rel="stylesheet" href="../../../../../resources/views/sneat-1.0.0/assets/vendor/fonts/boxicons.css">


  <!-- Core CSS -->
  <link rel="stylesheet" href="../../../../../resources/views/sneat-1.0.0/assets/vendor/css/core.css"
    class="template-customizer-core-css">
  <link rel="stylesheet" href="../../../../../resources/views/sneat-1.0.0/assets/vendor/css/theme-default.css"
    class="template-customizer-theme-css">
  <link rel="stylesheet" href="../../../../../resources/views/sneat-1.0.0/assets/css/demo.css">

  <!-- Vendors CSS -->
  <link rel="stylesheet"
    href="../../../../../resources/views/sneat-1.0.0/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css">


  <!-- Page CSS -->
  <!-- Page -->
  <link rel="stylesheet" href="../../../../../resources/views/sneat-1.0.0/assets/vendor/css/pages/page-auth.css">

  <!-- Helpers -->
  <script src="../assets/vendor/js/helpers.js"></script>
  <style type="text/css">
    .layout-menu-fixed .layout-navbar-full .layout-menu,
    .layout-page {
      padding-top: 0px !important;
    }

    .content-wrapper {
      padding-bottom: 0px !important;
    }
  </style>
  <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
  <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
  <script src="../assets/js/config.js"></script>

  <script type="text/javascript" src="https://a.omappapi.com/app/js/api.min.js" async="" data-user="252882"
    data-account="269977"></script>
  <link rel="stylesheet" href="https://a.omappapi.com/app/js/api.min.css" id="omapi-css" media="all">
</head>

<body>
  <div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
      <div class="authentication-inner">
        <!-- Register -->
        <div class="card">
          <div class="card-body">
            <!-- Logo -->
            <div class="app-brand justify-content-center">
              <a href="index.html" class="app-brand-link gap-2">
                <span class="app-brand-logo demo">

                  <svg class="w-[46px] h-[46px] text-gray-800 dark:text-white" aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M21 12a28.076 28.076 0 0 1-1.091 9M7.231 4.37a8.994 8.994 0 0 1 12.88 3.73M2.958 15S3 14.577 3 12a8.949 8.949 0 0 1 1.735-5.307m12.84 3.088A5.98 5.98 0 0 1 18 12a30 30 0 0 1-.464 6.232M6 12a6 6 0 0 1 9.352-4.974M4 21a5.964 5.964 0 0 1 1.01-3.328 5.15 5.15 0 0 0 .786-1.926m8.66 2.486a13.96 13.96 0 0 1-.962 2.683M7.5 19.336C9 17.092 9 14.845 9 12a3 3 0 1 1 6 0c0 .749 0 1.521-.031 2.311M12 12c0 3 0 6-2 9" />
                  </svg>

                </span>
                <span class="app-brand-text demo text-body fw-bold">Organize Lifes</span>
              </a>
            </div>
            <!-- /Logo -->
            <h4 class="mb-2" data-translate="welcome-login-message">Benvenuti in Organizzare la vita!</h4>
            <p class="mb-4" data-translate="login-message">Accedi al tuo account e inizia l'avventura</p>

            <form id="formAuthentication" method="post" class="mb-3" action="../html/signin" autocomplete="off">
              <div class="mb-3">
                <label for="email" class="form-label <?php echo $erroEmail ? 'text-danger' : ''; ?>"
                  data-translate="email">E-mail</label>
                <input type="text" class="form-control" id="email" name="email" data-translate-placeholder="email"
                  autofocus="">
              </div>
              <div class="mb-3 form-password-toggle">
                <div class="d-flex justify-content-between">
                  <label class="form-label <?php echo $erroSenha ? 'text-danger' : ''; ?>" for="password"
                    data-translate="password">Parola
                    d'ordine</label>
                </div>
                <div class="input-group input-group-merge">
                  <input type="password" id="password" class="form-control" name="password" placeholder="············"
                    aria-describedby="password">
                </div>
              </div>

              <div class="mb-3">
                <button class="btn btn-primary d-grid w-100" type="submit" >
                  <span data-translate="sign-in">Login</span></button>
              </div>
            </form>
            <style>
              .error {
                border-color: red;
              }
            </style>

            <p class="text-center">
              <span data-translate="new-question">Nuovo sulla nostra piattaforma?</span>
              <a href="../html/signup">
                <span data-translate="create-account">Creare un account</span>
              </a>
            </p>
            <p class="text-center">
              <span data-translate="back-home">
                Torniamo all'inizio</span>
              <a href="../">
                <span data-translate="home">
                  Inizio</span>
              </a>
            </p>
            <p class="text-center">
            <div class="btn-group" id="dropdown-icon-demo">
              <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                <i class="bx bx-globe me-1"></i> <span data-translate="languages">Languages</span>
              </button>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-lang="pt"><span
                      class="flag-icon flag-icon-pt flag-icon-squared"></span>Português</a></li>
                <li><a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-lang="es"><span
                      class="flag-icon flag-icon-es flag-icon-squared"></span>Español</a></li>
                <li><a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-lang="it"><span
                      class="flag-icon flag-icon-it flag-icon-suspred"></span>Italiano</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a href="javascript:void(0);" class="dropdown-item d-flex align-items-center"><i
                      class="bx bx-chevron-right scaleX-n1-rtl"></i>Separated link</a></li>
              </ul>
            </div>
            <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css" />
            </p>
          </div>
        </div>
        <!-- /Register -->
      </div>
    </div>
  </div>
  </div>



  <!-- / Content -->
  <script>
    // Função para definir um cookie com o idioma selecionado
    function setLanguageCookie(language) {
      document.cookie = `language=${language};path=/;`;
    }

    // Função para carregar as traduções com base no idioma selecionado ou armazenado em cookie
    function loadTranslations() {
      // Obtém o idioma armazenado no cookie, se existir
      const cookieLanguage = document.cookie.replace(/(?:(?:^|.*;\s*)language\s*=\s*([^;]*).*$)|^.*$/, "$1");

      // Define o idioma como o idioma armazenado no cookie ou padrão para 'en' (inglês)
      const language = cookieLanguage || 'en';

      // Carrega as traduções correspondentes ao idioma selecionado
      fetch(`../../../../../../../app/langs/lang_${language}.json`)
        .then(response => response.json())
        .then(data => {
          // Itera sobre as chaves do JSON e substitui o texto nas páginas HTML
          for (const key in data) {
            const elements = document.querySelectorAll(`[data-translate="${key}"]`);
            elements.forEach(element => {
              element.textContent = data[key];
            });
            const placeholders = document.querySelectorAll(`[data-translate-placeholder="${key}"]`);
            placeholders.forEach(element => {
              element.setAttribute('placeholder', data[key]);
            });
          }
        })
        .catch(error => console.error('Erro ao carregar traduções:', error));
    }

    // Event listener para alterar o idioma quando o usuário selecionar uma opção no dropdown
    document.querySelectorAll('.dropdown-item[data-lang]').forEach(item => {
      item.addEventListener('click', function () {
        const language = this.dataset.lang;
        setLanguageCookie(language); // Define o cookie com o idioma selecionado
        loadTranslations(); // Carrega as traduções correspondentes
      });
    });

    // Carrega as traduções ao carregar a página
    window.addEventListener('DOMContentLoaded', loadTranslations);
  </script>





  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->

  <script src="../../../../../resources/views/sneat-1.0.0/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="../../../../../resources/views/sneat-1.0.0/assets/vendor/libs/popper/popper.js"></script>
  <script src="../../../../../resources/views/sneat-1.0.0/assets/vendor/js/bootstrap.js"></script>
  <script
    src="../../../../../resources/views/sneat-1.0.0/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  <script src="../../../../../resources/views/sneat-1.0.0/assets/vendor/js/menu.js"></script>

  <!-- endbuild -->

  <!-- Vendors JS -->



  <!-- Main JS -->
  <script src="../../../../../resources/views/sneat-1.0.0/assets/js/main.js"></script>


  <!-- Page JS -->



  <!-- Place this tag in your head or just before your close body tag. -->
  <script async="" defer="" src="https://buttons.github.io/buttons.js"></script>







  <script type="text/javascript" id="">console.log("TS:GTM Worked!");</script>
  <script type="text/javascript"
    id="">(function (b, c, d) { var a = b.createElement("script"); a.type = "text/javascript"; a.src = "https://a.omappapi.com/app/js/api.min.js"; a.async = !0; a.dataset.user = c; a.dataset.account = d; b.getElementsByTagName("head")[0].appendChild(a) })(document, 252882, 269977);</script>
  <div id="om-mmosgju0tkru8ajiwhig-holder"></div>
</body>

</html>